// frontend/src/lib/components/film/LetterboxdRatingReveal.svelte
<script lang="ts">
	import { browser } from '$app/environment';

	let { rating, filmId }: { rating: number; filmId: string } = $props();

	const LETTERBOXD_GREEN = '#00E054';
	const LETTERBOXD_ORANGE = '#FF8000';

	const storageKey = `letterboxd-revealed-${filmId}`;

	let isRevealed = $state(
		browser ? sessionStorage.getItem(storageKey) === 'true' : false
	);

	function reveal() {
		if (isRevealed) return;
		isRevealed = true;
		if (browser) {
			sessionStorage.setItem(storageKey, 'true');
		}
	}

	// Star calculation
	const fullStars = $derived(Math.floor(rating));
	const hasHalfStar = $derived(rating % 1 >= 0.25 && rating % 1 < 0.75);
	const roundedUp = $derived(rating % 1 >= 0.75);
	const displayStars = $derived(roundedUp ? fullStars + 1 : fullStars);
	const emptyStars = $derived(5 - displayStars - (hasHalfStar ? 1 : 0));
</script>

{#if isRevealed}
	<div class="rating-revealed">
		<div class="stars">
			{#each Array(displayStars) as _, i}
				<svg viewBox="0 0 24 24" class="star" fill={LETTERBOXD_ORANGE} stroke={LETTERBOXD_ORANGE} stroke-width="1.5">
					<path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"/>
				</svg>
			{/each}
			{#if hasHalfStar}
				<svg viewBox="0 0 24 24" class="star">
					<defs>
						<linearGradient id="half-{filmId}">
							<stop offset="50%" stop-color={LETTERBOXD_ORANGE} />
							<stop offset="50%" stop-color="transparent" />
						</linearGradient>
					</defs>
					<path fill="url(#half-{filmId})" stroke={LETTERBOXD_ORANGE} stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"/>
				</svg>
			{/if}
			{#each Array(Math.max(0, emptyStars)) as _, i}
				<svg viewBox="0 0 24 24" class="star" fill="transparent" stroke="#666" stroke-width="1.5">
					<path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"/>
				</svg>
			{/each}
		</div>
		<span class="rating-value" style="color: {LETTERBOXD_GREEN}">{rating.toFixed(1)}</span>
	</div>
{:else}
	<button class="reveal-btn" onclick={reveal} aria-label="Show Letterboxd rating">
		<svg class="eye-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
			<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/>
			<circle cx="12" cy="12" r="3"/>
		</svg>
		<span>SHOW RATING</span>
	</button>
{/if}

<style>
	.rating-revealed {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.375rem 0.75rem;
		border: 1px solid var(--color-border-subtle);
		background: var(--color-surface);
	}

	.stars {
		display: flex;
		align-items: center;
		gap: 2px;
	}

	.star {
		width: 14px;
		height: 14px;
	}

	.rating-value {
		font-family: var(--font-mono);
		font-size: var(--font-size-sm);
		font-weight: 600;
		font-variant-numeric: tabular-nums;
	}

	.reveal-btn {
		display: inline-flex;
		align-items: center;
		gap: 0.375rem;
		padding: 0.375rem 0.75rem;
		font-size: var(--font-size-xs);
		font-weight: 500;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--color-text-tertiary);
		background: var(--color-surface);
		border: 1px solid var(--color-border-subtle);
		cursor: pointer;
		transition: color var(--duration-fast) var(--ease-sharp),
			border-color var(--duration-fast) var(--ease-sharp);
	}

	.reveal-btn:hover {
		color: var(--color-text);
		border-color: var(--color-border);
	}

	.eye-icon {
		flex-shrink: 0;
	}
</style>

// src/components/film/letterboxd-rating-reveal.tsx
/**
 * Letterboxd Rating Reveal Component
 *
 * A simple button that reveals the Letterboxd rating on click.
 * Rating is hidden by default to respect users who prefer not
 * to see ratings before watching a film.
 */

"use client";

import { useState } from "react";
import { cn } from "@/lib/cn";
import { Eye } from "lucide-react";

interface LetterboxdRatingRevealProps {
  rating: number; // 0-5 scale
  filmId: string;
  className?: string;
}

// Letterboxd brand colors
const LETTERBOXD_GREEN = "#00E054";
const LETTERBOXD_ORANGE = "#FF8000";

// Use session storage to remember which ratings have been revealed
const getRevealedKey = (filmId: string) => `letterboxd-revealed-${filmId}`;

export function LetterboxdRatingReveal({
  rating,
  filmId,
  className
}: LetterboxdRatingRevealProps) {
  // Check if this rating was already revealed in this session
  const [isRevealed, setIsRevealed] = useState(() => {
    if (typeof window === "undefined") return false;
    return sessionStorage.getItem(getRevealedKey(filmId)) === "true";
  });

  const handleReveal = () => {
    if (isRevealed) return;
    setIsRevealed(true);
    if (typeof window !== "undefined") {
      sessionStorage.setItem(getRevealedKey(filmId), "true");
    }
  };

  // Generate star display
  const fullStars = Math.floor(rating);
  const hasHalfStar = rating % 1 >= 0.25 && rating % 1 < 0.75;
  const roundedUp = rating % 1 >= 0.75;
  const displayStars = roundedUp ? fullStars + 1 : fullStars;
  const emptyStars = 5 - displayStars - (hasHalfStar ? 1 : 0);

  if (isRevealed) {
    // Show the rating inline
    return (
      <div
        className={cn(
          "inline-flex items-center gap-2 px-3 py-1.5 rounded-lg",
          "text-sm",
          "bg-background-tertiary",
          "border border-border-subtle",
          className
        )}
      >
        {/* Stars */}
        <div className="flex items-center gap-0.5">
          {[...Array(displayStars)].map((_, i) => (
            <StarIcon key={`full-${i}`} filled className="w-3.5 h-3.5" />
          ))}
          {hasHalfStar && <HalfStarIcon className="w-3.5 h-3.5" />}
          {[...Array(emptyStars)].map((_, i) => (
            <StarIcon key={`empty-${i}`} filled={false} className="w-3.5 h-3.5" />
          ))}
        </div>
        {/* Numeric rating */}
        <span
          className="font-medium tabular-nums"
          style={{ color: LETTERBOXD_GREEN }}
        >
          {rating.toFixed(1)}
        </span>
      </div>
    );
  }

  return (
    <button
      onClick={handleReveal}
      className={cn(
        "inline-flex items-center gap-2 px-3 py-1.5 rounded-lg",
        "text-sm text-text-tertiary hover:text-text-primary",
        "bg-background-tertiary hover:bg-surface-overlay-hover",
        "border border-border-subtle hover:border-border-default",
        "transition-all cursor-pointer",
        "focus:outline-none focus:ring-2 focus:ring-accent-primary/40",
        className
      )}
      aria-label="Show Letterboxd rating"
    >
      <Eye className="w-3.5 h-3.5" />
      <span className="font-medium">Show rating</span>
    </button>
  );
}

// Star SVG components
function StarIcon({ filled, className }: { filled: boolean; className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      fill={filled ? LETTERBOXD_ORANGE : "transparent"}
      stroke={filled ? LETTERBOXD_ORANGE : "#666"}
      strokeWidth={1.5}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"
      />
    </svg>
  );
}

function HalfStarIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className}>
      <defs>
        <linearGradient id="halfStarGradient">
          <stop offset="50%" stopColor={LETTERBOXD_ORANGE} />
          <stop offset="50%" stopColor="transparent" />
        </linearGradient>
      </defs>
      <path
        fill="url(#halfStarGradient)"
        stroke={LETTERBOXD_ORANGE}
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"
      />
    </svg>
  );
}
