// src/components/layout/header/film-type-filter.tsx
"use client";

import { Film, Sparkles, History } from "lucide-react";
import { cn } from "@/lib/cn";
import { useFilters } from "@/stores/filters";

/** Film Type Filter Component - All / New Releases / Repertory */
export function FilmTypeFilter({ mounted, fullWidth }: { mounted: boolean; fullWidth?: boolean }) {
  const { programmingTypes, setProgrammingTypes } = useFilters();

  // Determine current selection
  const currentType = mounted
    ? programmingTypes.length === 0
      ? "all"
      : programmingTypes.includes("repertory")
      ? "repertory"
      : programmingTypes.includes("new_release")
      ? "new_release"
      : "all"
    : "all";

  const handleSelect = (type: "all" | "new_release" | "repertory") => {
    if (type === "all") {
      setProgrammingTypes([]);
    } else {
      setProgrammingTypes([type]);
    }
  };

  const options = [
    { value: "all", label: "All", icon: Film },
    { value: "new_release", label: "New", icon: Sparkles },
    { value: "repertory", label: "Repertory", icon: History },
  ] as const;

  return (
    <div
      role="group"
      aria-label="Film type filter"
      className={cn(
        "flex rounded-lg border border-border-default bg-background-tertiary overflow-hidden",
        fullWidth && "w-full"
      )}
    >
      {options.map((option) => {
        const Icon = option.icon;
        const isActive = currentType === option.value;
        return (
          <button
            key={option.value}
            onClick={() => handleSelect(option.value)}
            aria-pressed={isActive}
            className={cn(
              "flex items-center justify-center gap-1.5 px-3 py-2.5 text-sm font-medium transition-colors",
              "border-r border-border-default last:border-r-0",
              fullWidth && "flex-1",
              isActive
                ? "bg-accent-primary text-text-inverse"
                : "text-text-secondary hover:text-text-primary hover:bg-background-hover"
            )}
          >
            <Icon className="w-4 h-4" aria-hidden="true" />
            <span>{option.label}</span>
          </button>
        );
      })}
    </div>
  );
}

// frontend/src/lib/components/filters/FilmTypeFilter.svelte
<script lang="ts">
	import { filters } from '$lib/stores/filters.svelte';

	const options = [
		{ value: 'all', label: 'ALL' },
		{ value: 'new', label: 'NEW' },
		{ value: 'repertory', label: 'REPERTORY' }
	];

	const selected = $derived.by(() => {
		if (filters.programmingTypes.length === 0) return 'all';
		if (filters.programmingTypes.includes('new_release')) return 'new';
		if (filters.programmingTypes.includes('repertory')) return 'repertory';
		return 'all';
	});

	function handleSelect(value: string) {
		if (value === 'all') {
			filters.programmingTypes = [];
		} else if (value === 'new') {
			filters.programmingTypes = ['new_release'];
		} else if (value === 'repertory') {
			filters.programmingTypes = ['repertory'];
		}
	}
</script>

<div class="type-filter" role="tablist" aria-label="Film type">
	{#each options as option}
		<button
			role="tab"
			aria-selected={selected === option.value}
			class="type-tab"
			class:active={selected === option.value}
			onclick={() => handleSelect(option.value)}
		>
			{option.label}
		</button>
	{/each}
</div>

<style>
	.type-filter {
		display: flex;
		gap: 0;
	}

	.type-tab:first-child {
		padding-left: 0;
	}

	.type-tab {
		padding: 0.375rem 0.625rem;
		font-size: var(--font-size-xs);
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-text-tertiary);
		background: transparent;
		border: none;
		border-bottom: 2px solid transparent;
		cursor: pointer;
		transition: color var(--duration-fast) var(--ease-sharp),
			border-color var(--duration-fast) var(--ease-sharp);
	}

	.type-tab:hover {
		color: var(--color-text);
	}

	.type-tab.active {
		color: var(--color-text);
		border-bottom-color: var(--color-accent);
	}
</style>
