// src/components/reachable/reachable-results.tsx
/**
 * Reachable Results Component
 * Displays filtered screenings with travel time and "leave by" information
 */

"use client";

import { useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { Clock, MapPin, Train, Calendar, ExternalLink, Footprints, Bike } from "lucide-react";
import { format } from "date-fns";
import { cn } from "@/lib/cn";
import {
  groupByUrgency,
  getUrgencyLabel,
  formatLeaveBy,
  type ReachableScreening,
  type UrgencyGroup,
} from "@/lib/travel-time";
import { formatTravelTime } from "@/stores/reachable";

interface ReachableResultsProps {
  screenings: ReachableScreening[];
  totalScreenings: number;
  finishedByTime: Date;
}

export function ReachableResults({
  screenings,
  totalScreenings,
  finishedByTime,
}: ReachableResultsProps) {
  // Group screenings by urgency
  const groups = useMemo(() => groupByUrgency(screenings), [screenings]);

  // Empty state
  if (screenings.length === 0) {
    return (
      <div className="p-8 bg-background-secondary border border-border-subtle rounded-lg text-center">
        <Calendar className="w-10 h-10 text-text-tertiary mx-auto mb-4" />
        <h2 className="text-lg font-medium text-text-primary mb-2">
          No reachable screenings
        </h2>
        <p className="text-text-secondary text-sm max-w-md mx-auto">
          No screenings finish before{" "}
          <span className="font-medium">{format(finishedByTime, "h:mm a")}</span>{" "}
          that you can reach in time. Try a later deadline or different travel mode.
        </p>
        <p className="text-text-tertiary text-xs mt-4">
          Checked {totalScreenings} screenings across all cinemas
        </p>
      </div>
    );
  }

  const urgencyOrder: UrgencyGroup[] = ["leave_soon", "leave_within_hour", "later"];

  return (
    <div className="space-y-8">
      {urgencyOrder.map((urgency) => {
        const groupScreenings = groups[urgency];
        if (groupScreenings.length === 0) return null;

        return (
          <div key={urgency}>
            {/* Group Header */}
            <div className="flex items-center gap-2 mb-4">
              <h2
                className={cn(
                  "text-sm font-semibold uppercase tracking-wide",
                  urgency === "leave_soon" && "text-error-text",
                  urgency === "leave_within_hour" && "text-warning-text",
                  urgency === "later" && "text-text-secondary"
                )}
              >
                {getUrgencyLabel(urgency)}
              </h2>
              <span className="text-xs text-text-tertiary">
                ({groupScreenings.length})
              </span>
            </div>

            {/* Screening Cards */}
            <div className="space-y-3">
              {groupScreenings.map((screening) => (
                <ReachableScreeningCard
                  key={screening.id}
                  screening={screening}
                  urgency={urgency}
                />
              ))}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// Individual screening card
function ReachableScreeningCard({
  screening,
  urgency,
}: {
  screening: ReachableScreening;
  urgency: UrgencyGroup;
}) {
  const screeningTime = new Date(screening.datetime);

  return (
    <div className="flex gap-4 p-4 bg-background-secondary border border-border-subtle rounded-lg hover:border-border-default transition-colors">
      {/* Poster */}
      <div className="flex-shrink-0 w-16 sm:w-20">
        {screening.film.posterUrl ? (
          <Image
            src={screening.film.posterUrl}
            alt={screening.film.title}
            width={80}
            height={120}
            className="w-full aspect-[2/3] object-cover rounded"
          />
        ) : (
          <div className="w-full aspect-[2/3] bg-background-tertiary rounded flex items-center justify-center">
            <span className="text-text-tertiary text-xs">No poster</span>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0">
        {/* Leave By Badge - Most Important! */}
        <div
          className={cn(
            "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold mb-2",
            urgency === "leave_soon" && "bg-error-surface text-error-text",
            urgency === "leave_within_hour" && "bg-warning-surface text-warning-text",
            urgency === "later" && "bg-accent-primary/10 text-accent-primary"
          )}
        >
          <Clock className="w-3.5 h-3.5" />
          {formatLeaveBy(screening.leaveBy, screening.minutesUntilLeave)}
        </div>

        {/* Film Title */}
        <Link href={`/film/${screening.film.id}`}>
          <h3 className="font-medium text-text-primary hover:text-accent-primary transition-colors line-clamp-1">
            {screening.film.title}
            {screening.film.year && (
              <span className="text-text-tertiary font-normal ml-1">
                ({screening.film.year})
              </span>
            )}
          </h3>
        </Link>

        {/* Screening Details */}
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-1.5 text-sm text-text-secondary">
          {/* Time */}
          <span className="font-medium text-text-primary">
            {format(screeningTime, "h:mm a")}
          </span>

          {/* Cinema */}
          <span className="flex items-center gap-1">
            <MapPin className="w-3.5 h-3.5" />
            {screening.cinema.shortName || screening.cinema.name}
          </span>

          {/* Travel Time */}
          <span className="flex items-center gap-1 text-accent-primary">
            {screening.travelMode === "walking" ? (
              <Footprints className="w-3.5 h-3.5" />
            ) : screening.travelMode === "bicycling" ? (
              <Bike className="w-3.5 h-3.5" />
            ) : (
              <Train className="w-3.5 h-3.5" />
            )}
            {formatTravelTime(screening.travelMinutes)}
          </span>

          {/* Runtime */}
          {screening.film.runtime && (
            <span className="text-text-tertiary">
              {screening.film.runtime} min
            </span>
          )}

          {/* Format */}
          {screening.format && (
            <span className="text-xs px-1.5 py-0.5 rounded bg-background-tertiary text-text-secondary">
              {screening.format}
            </span>
          )}
        </div>

        {/* Booking Link */}
        {screening.bookingUrl && (
          <a
            href={screening.bookingUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 mt-2 text-xs text-accent-primary hover:underline"
          >
            Book tickets
            <ExternalLink className="w-3 h-3" />
          </a>
        )}
      </div>
    </div>
  );
}

// frontend/src/lib/components/reachable/ReachableResults.svelte
<script lang="ts">
	import {
		groupByUrgency,
		getUrgencyLabel,
		formatLeaveBy,
		formatTravelTime,
		type ReachableScreening,
		type UrgencyGroup
	} from '$lib/travel-time';
	import { formatTime } from '$lib/utils';

	let {
		screenings = [],
		totalScreenings = 0,
		finishedByTime
	}: {
		screenings: ReachableScreening[];
		totalScreenings: number;
		finishedByTime: Date;
	} = $props();

	const groups = $derived(groupByUrgency(screenings));

	const urgencyOrder: UrgencyGroup[] = ['leave_soon', 'leave_within_hour', 'later'];

	function urgencyClass(urgency: UrgencyGroup): string {
		switch (urgency) {
			case 'leave_soon':
				return 'urgency-soon';
			case 'leave_within_hour':
				return 'urgency-hour';
			default:
				return 'urgency-later';
		}
	}

	function finishedByStr(date: Date): string {
		return date.toLocaleTimeString('en-GB', {
			hour: '2-digit',
			minute: '2-digit',
			hour12: false
		});
	}
</script>

{#if screenings.length === 0}
	<!-- Empty state -->
	<div class="empty-state">
		<svg class="empty-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<rect x="3" y="4" width="18" height="18" />
			<line x1="16" y1="2" x2="16" y2="6" />
			<line x1="8" y1="2" x2="8" y2="6" />
			<line x1="3" y1="10" x2="21" y2="10" />
		</svg>
		<h2 class="empty-title">NO REACHABLE SCREENINGS</h2>
		<p class="empty-desc">
			No screenings finish before
			<strong>{finishedByStr(finishedByTime)}</strong>
			that you can reach in time. Try a later deadline or different travel mode.
		</p>
		<p class="empty-meta">
			Checked {totalScreenings} screenings across all cinemas
		</p>
	</div>
{:else}
	<div class="results">
		<!-- Summary -->
		<p class="summary">
			<strong>{screenings.length}</strong> reachable screenings from {totalScreenings} total
		</p>

		{#each urgencyOrder as urgency (urgency)}
			{@const groupScreenings = groups[urgency]}
			{#if groupScreenings.length > 0}
				<div class="urgency-group">
					<!-- Group header -->
					<div class="group-header">
						<h2 class="group-label {urgencyClass(urgency)}">
							{getUrgencyLabel(urgency)}
						</h2>
						<span class="group-count">({groupScreenings.length})</span>
					</div>

					<!-- Screening cards -->
					<div class="cards">
						{#each groupScreenings as screening (screening.id)}
							{@const screeningTime = formatTime(screening.datetime)}
							<div class="card">
								<!-- Poster -->
								<div class="card-poster">
									{#if screening.film.posterUrl}
										<img
											src={screening.film.posterUrl}
											alt={screening.film.title}
											class="poster-img"
											loading="lazy"
										/>
									{:else}
										<div class="poster-placeholder">
											<span>NO POSTER</span>
										</div>
									{/if}
								</div>

								<!-- Content -->
								<div class="card-content">
									<!-- Leave-by badge -->
									<div class="leave-badge {urgencyClass(urgency)}">
										<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
											<circle cx="12" cy="12" r="10" />
											<polyline points="12 6 12 12 16 14" />
										</svg>
										{formatLeaveBy(screening.leaveBy, screening.minutesUntilLeave)}
									</div>

									<!-- Film title -->
									<a href="/film/{screening.film.id}" class="film-title">
										{screening.film.title}
										{#if screening.film.year}
											<span class="film-year">({screening.film.year})</span>
										{/if}
									</a>

									<!-- Screening details -->
									<div class="details">
										<!-- Time -->
										<span class="detail-time">{screeningTime}</span>

										<!-- Cinema -->
										<span class="detail-cinema">
											<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
												<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
												<circle cx="12" cy="10" r="3" />
											</svg>
											{screening.cinema.shortName || screening.cinema.name}
										</span>

										<!-- Travel time -->
										<span class="detail-travel">
											{#if screening.travelMode === 'walking'}
												<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="5" r="1.5" fill="currentColor" /><path d="M10 21l1.5-7.5L14 16v5" /><path d="M10 13.5l-2 3.5" /><path d="M14 8l-2.5 5.5" /><path d="M10 8.5l2-1" /></svg>
											{:else if screening.travelMode === 'bicycling'}
												<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="5.5" cy="17.5" r="3.5" /><circle cx="18.5" cy="17.5" r="3.5" /><path d="M15 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" fill="currentColor" /><path d="M12 17.5V14l-3-3 4-3 2 3h2" /></svg>
											{:else}
												<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect x="4" y="3" width="16" height="16" /><path d="M4 11h16" /><path d="M12 3v8" /><circle cx="8" cy="15" r="1" fill="currentColor" /><circle cx="16" cy="15" r="1" fill="currentColor" /><path d="M8 19l-2 3" /><path d="M16 19l2 3" /></svg>
											{/if}
											{formatTravelTime(screening.travelMinutes)}
										</span>

										<!-- Runtime -->
										{#if screening.film.runtime}
											<span class="detail-runtime">{screening.film.runtime} min</span>
										{/if}

										<!-- Format badge -->
										{#if screening.format}
											<span class="detail-format">{screening.format}</span>
										{/if}
									</div>

									<!-- Booking link -->
									{#if screening.bookingUrl}
										<a
											href={screening.bookingUrl}
											target="_blank"
											rel="noopener noreferrer"
											class="booking-link"
										>
											BOOK TICKETS
											<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
												<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
												<polyline points="15 3 21 3 21 9" />
												<line x1="10" y1="14" x2="21" y2="3" />
											</svg>
										</a>
									{/if}
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}
		{/each}
	</div>
{/if}

<style>
	/* ── Empty state ── */
	.empty-state {
		padding: 3rem 1.5rem;
		border: 1px solid var(--color-border-subtle);
		background: var(--color-surface);
		text-align: center;
	}

	.empty-icon {
		width: 2.5rem;
		height: 2.5rem;
		color: var(--color-text-tertiary);
		margin: 0 auto 1rem;
	}

	.empty-title {
		font-size: var(--font-size-sm);
		font-weight: 700;
		font-family: var(--font-display);
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-text);
		margin-bottom: 0.5rem;
	}

	.empty-desc {
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
		max-width: 28rem;
		margin: 0 auto;
	}

	.empty-desc strong {
		color: var(--color-text);
		font-family: var(--font-mono);
	}

	.empty-meta {
		font-size: var(--font-size-xs);
		color: var(--color-text-tertiary);
		margin-top: 1rem;
	}

	/* ── Results ── */
	.results {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.summary {
		font-size: var(--font-size-xs);
		color: var(--color-text-tertiary);
		font-family: var(--font-mono);
		text-transform: uppercase;
		letter-spacing: 0.04em;
	}

	.summary strong {
		color: var(--color-text);
	}

	/* ── Urgency groups ── */
	.urgency-group {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.group-header {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.group-label {
		font-size: var(--font-size-xs);
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.08em;
	}

	.group-count {
		font-size: var(--font-size-xs);
		color: var(--color-text-tertiary);
	}

	.urgency-soon {
		color: var(--color-accent);
	}

	.urgency-hour {
		color: var(--color-text);
	}

	.urgency-later {
		color: var(--color-text-secondary);
	}

	/* ── Cards ── */
	.cards {
		display: flex;
		flex-direction: column;
		gap: 0;
	}

	.card {
		display: flex;
		gap: 1rem;
		padding: 1rem;
		border: 1px solid var(--color-border-subtle);
		background: var(--color-surface);
		transition: border-color var(--duration-fast) var(--ease-sharp);
	}

	.card + .card {
		margin-top: -1px;
	}

	.card:hover {
		border-color: var(--color-text);
		z-index: 1;
	}

	/* ── Poster ── */
	.card-poster {
		flex-shrink: 0;
		width: 4rem;
	}

	@media (min-width: 640px) {
		.card-poster {
			width: 5rem;
		}
	}

	.poster-img {
		width: 100%;
		aspect-ratio: 2/3;
		object-fit: cover;
		display: block;
	}

	.poster-placeholder {
		width: 100%;
		aspect-ratio: 2/3;
		background: var(--color-bg-subtle);
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.poster-placeholder span {
		font-size: 0.5rem;
		color: var(--color-text-tertiary);
		text-transform: uppercase;
		letter-spacing: 0.08em;
	}

	/* ── Content ── */
	.card-content {
		flex: 1;
		min-width: 0;
	}

	/* ── Leave-by badge ── */
	.leave-badge {
		display: inline-flex;
		align-items: center;
		gap: 0.375rem;
		padding: 0.25rem 0.5rem;
		font-size: var(--font-size-xs);
		font-weight: 700;
		font-family: var(--font-mono);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		margin-bottom: 0.5rem;
	}

	.leave-badge svg {
		width: 0.875rem;
		height: 0.875rem;
	}

	.leave-badge.urgency-soon {
		background: color-mix(in srgb, var(--color-accent) 15%, transparent);
		color: var(--color-accent);
	}

	.leave-badge.urgency-hour {
		background: var(--color-bg-subtle);
		color: var(--color-text);
	}

	.leave-badge.urgency-later {
		background: var(--color-bg-subtle);
		color: var(--color-text-secondary);
	}

	/* ── Film title ── */
	.film-title {
		display: block;
		font-weight: 600;
		font-size: var(--font-size-sm);
		color: var(--color-text);
		text-decoration: none;
		line-height: 1.3;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		transition: color var(--duration-fast) var(--ease-sharp);
	}

	.film-title:hover {
		color: var(--color-accent);
	}

	.film-year {
		color: var(--color-text-tertiary);
		font-weight: 400;
		margin-left: 0.25rem;
	}

	/* ── Details row ── */
	.details {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 0.75rem;
		margin-top: 0.375rem;
		font-size: var(--font-size-xs);
		color: var(--color-text-secondary);
	}

	.detail-time {
		font-family: var(--font-mono);
		font-weight: 600;
		color: var(--color-text);
	}

	.detail-cinema {
		display: flex;
		align-items: center;
		gap: 0.25rem;
	}

	.detail-cinema svg {
		width: 0.875rem;
		height: 0.875rem;
	}

	.detail-travel {
		display: flex;
		align-items: center;
		gap: 0.25rem;
		color: var(--color-accent);
		font-family: var(--font-mono);
	}

	.detail-travel svg {
		width: 0.875rem;
		height: 0.875rem;
	}

	.detail-runtime {
		color: var(--color-text-tertiary);
		font-family: var(--font-mono);
	}

	.detail-format {
		font-size: 0.625rem;
		padding: 0.125rem 0.375rem;
		background: var(--color-bg-subtle);
		color: var(--color-text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		font-family: var(--font-mono);
	}

	/* ── Booking link ── */
	.booking-link {
		display: inline-flex;
		align-items: center;
		gap: 0.25rem;
		margin-top: 0.5rem;
		font-size: var(--font-size-xs);
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-accent);
		text-decoration: none;
		transition: opacity var(--duration-fast) var(--ease-sharp);
	}

	.booking-link:hover {
		opacity: 0.7;
	}

	.booking-link svg {
		width: 0.75rem;
		height: 0.75rem;
	}
</style>
