// frontend/src/lib/components/reachable/DeadlinePicker.svelte
<script lang="ts">
	let {
		value = null,
		onchange
	}: {
		value: Date | null;
		onchange: (time: Date | null) => void;
	} = $props();

	interface TimePreset {
		label: string;
		hour: number;
		minute: number;
		nextDay?: boolean;
	}

	const PRESETS: TimePreset[] = [
		{ label: '6 PM', hour: 18, minute: 0 },
		{ label: '8 PM', hour: 20, minute: 0 },
		{ label: '10 PM', hour: 22, minute: 0 },
		{ label: 'MIDNIGHT', hour: 0, minute: 0, nextDay: true }
	];

	// Check which preset is selected
	const selectedPresetLabel = $derived.by(() => {
		if (!value) return null;
		const hour = value.getHours();
		const minute = value.getMinutes();
		const found = PRESETS.find((p) => {
			const presetHour = p.nextDay ? 0 : p.hour;
			return presetHour === hour && p.minute === minute;
		});
		return found?.label ?? null;
	});

	// Calculate countdown
	const timeRemaining = $derived.by(() => {
		if (!value) return null;
		const now = new Date();
		const diffMs = value.getTime() - now.getTime();
		if (diffMs <= 0) return null;
		const mins = Math.round(diffMs / 60_000);
		const hours = Math.floor(mins / 60);
		const remainingMins = mins % 60;

		if (hours === 0) return `${remainingMins}m remaining`;
		if (remainingMins === 0) return `${hours}h remaining`;
		return `${hours}h ${remainingMins}m remaining`;
	});

	function handlePreset(preset: TimePreset) {
		const now = new Date();
		const date = new Date();
		date.setHours(preset.hour, preset.minute, 0, 0);

		// If time has passed today or explicitly next day
		if (date <= now || preset.nextDay) {
			date.setDate(date.getDate() + 1);
		}

		onchange(date);
	}

	function formatSelectedTime(date: Date): string {
		const now = new Date();
		const todayStr = now.toLocaleDateString('en-CA', { timeZone: 'Europe/London' });
		const tomorrowDate = new Date(now);
		tomorrowDate.setDate(tomorrowDate.getDate() + 1);
		const tomorrowStr = tomorrowDate.toLocaleDateString('en-CA', { timeZone: 'Europe/London' });
		const targetStr = date.toLocaleDateString('en-CA', { timeZone: 'Europe/London' });

		const timeStr = date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false });

		if (targetStr === todayStr) return `Today at ${timeStr}`;
		if (targetStr === tomorrowStr) return `Tomorrow at ${timeStr}`;
		return date.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' }) + ` at ${timeStr}`;
	}
</script>

<div class="deadline-picker">
	<span class="label">FINISHED BY</span>

	<div class="presets">
		{#each PRESETS as preset (preset.label)}
			{@const isSelected = selectedPresetLabel === preset.label}
			<button
				class="preset-btn"
				class:preset-selected={isSelected}
				onclick={() => handlePreset(preset)}
			>
				{preset.label}
			</button>
		{/each}
	</div>

	{#if value}
		<div class="selected-display">
			<span class="selected-time">{formatSelectedTime(value)}</span>
			{#if timeRemaining}
				<span class="countdown">{timeRemaining}</span>
			{/if}
		</div>
	{/if}
</div>

<style>
	.deadline-picker {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.label {
		font-size: var(--font-size-xs);
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-text-tertiary);
	}

	.presets {
		display: flex;
		gap: 0;
	}

	.preset-btn {
		flex: 1;
		padding: 0.625rem 0.5rem;
		font-size: var(--font-size-xs);
		font-weight: 600;
		font-family: var(--font-mono);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		border: 1px solid var(--color-border-subtle);
		background: var(--color-surface);
		color: var(--color-text-secondary);
		cursor: pointer;
		transition:
			background var(--duration-fast) var(--ease-sharp),
			color var(--duration-fast) var(--ease-sharp),
			border-color var(--duration-fast) var(--ease-sharp);
	}

	/* Collapse adjacent borders */
	.preset-btn + .preset-btn {
		margin-left: -1px;
	}

	.preset-btn:hover {
		color: var(--color-text);
		border-color: var(--color-text);
		z-index: 1;
	}

	.preset-selected {
		background: var(--color-screening-bg);
		color: var(--color-screening-text);
		border-color: var(--color-screening-bg);
		z-index: 2;
	}

	.preset-selected:hover {
		background: var(--color-screening-bg);
		color: var(--color-screening-text);
		border-color: var(--color-screening-bg);
	}

	.selected-display {
		display: flex;
		align-items: center;
		justify-content: space-between;
		font-size: var(--font-size-xs);
	}

	.selected-time {
		color: var(--color-text);
		font-family: var(--font-mono);
	}

	.countdown {
		color: var(--color-accent);
		font-weight: 600;
		font-family: var(--font-mono);
	}
</style>

// src/components/reachable/deadline-picker.tsx
/**
 * Deadline Picker Component
 * Select the time you need to be free by
 */

"use client";

import { useState, useMemo } from "react";
import { Clock, ChevronDown } from "lucide-react";
import { format, setHours, setMinutes, differenceInMinutes, addDays, isToday, isTomorrow } from "date-fns";
import { cn } from "@/lib/cn";

interface DeadlinePickerProps {
  value: Date | null;
  onChange: (time: Date | null) => void;
}

// Preset times for quick selection
interface TimePreset {
  label: string;
  hour: number;
  minute: number;
  nextDay?: boolean;
}

const PRESETS: TimePreset[] = [
  { label: "6pm", hour: 18, minute: 0 },
  { label: "8pm", hour: 20, minute: 0 },
  { label: "10pm", hour: 22, minute: 0 },
  { label: "Midnight", hour: 0, minute: 0, nextDay: true },
];

export function DeadlinePicker({ value, onChange }: DeadlinePickerProps) {
  const [showCustom, setShowCustom] = useState(false);
  const [customHour, setCustomHour] = useState("21");
  const [customMinute, setCustomMinute] = useState("00");

  const now = new Date();

  // Check which preset is currently selected
  const selectedPreset = useMemo(() => {
    if (!value) return null;
    const hour = value.getHours();
    const minute = value.getMinutes();
    return PRESETS.find((p) => {
      const presetHour = p.nextDay === true ? 0 : p.hour;
      return presetHour === hour && p.minute === minute;
    });
  }, [value]);

  // Calculate time remaining
  const timeRemaining = useMemo(() => {
    if (!value) return null;
    const mins = differenceInMinutes(value, now);
    if (mins <= 0) return null;

    const hours = Math.floor(mins / 60);
    const remainingMins = mins % 60;

    if (hours === 0) return `${remainingMins}m remaining`;
    if (remainingMins === 0) return `${hours}h remaining`;
    return `${hours}h ${remainingMins}m remaining`;
  }, [value, now]);

  // Handle preset selection
  const handlePreset = (preset: TimePreset) => {
    let date = new Date();
    date = setHours(date, preset.hour);
    date = setMinutes(date, preset.minute);
    date.setSeconds(0);
    date.setMilliseconds(0);

    // If the time has passed today, use tomorrow
    if (date <= now || preset.nextDay === true) {
      date = addDays(date, 1);
    }

    onChange(date);
    setShowCustom(false);
  };

  // Handle custom time
  const handleCustomTime = () => {
    const hour = parseInt(customHour, 10);
    const minute = parseInt(customMinute, 10);

    if (isNaN(hour) || isNaN(minute)) return;

    let date = new Date();
    date = setHours(date, hour);
    date = setMinutes(date, minute);
    date.setSeconds(0);
    date.setMilliseconds(0);

    // If the time has passed today, use tomorrow
    if (date <= now) {
      date = addDays(date, 1);
    }

    onChange(date);
    setShowCustom(false);
  };

  // Format selected time for display
  const formatSelectedTime = (date: Date) => {
    const timeStr = format(date, "HH:mm");
    if (isToday(date)) {
      return `Today at ${timeStr}`;
    }
    if (isTomorrow(date)) {
      return `Tomorrow at ${timeStr}`;
    }
    return format(date, "EEE d MMM 'at' HH:mm");
  };

  return (
    <div className="space-y-3">
      {/* Preset Buttons */}
      <div className="flex gap-2 flex-wrap">
        {PRESETS.map((preset) => {
          const isSelected = selectedPreset?.label === preset.label;
          return (
            <button
              key={preset.label}
              onClick={() => handlePreset(preset)}
              className={cn(
                "px-4 py-2 rounded-lg border text-sm font-medium transition-colors",
                isSelected
                  ? "bg-accent-primary text-text-inverse border-accent-primary"
                  : "bg-background-secondary text-text-secondary border-border-default hover:border-accent-primary hover:text-text-primary"
              )}
            >
              {preset.label}
            </button>
          );
        })}

        {/* Custom Button */}
        <button
          onClick={() => setShowCustom(!showCustom)}
          className={cn(
            "px-4 py-2 rounded-lg border text-sm font-medium transition-colors flex items-center gap-1.5",
            showCustom || (!selectedPreset && value)
              ? "bg-accent-primary text-text-inverse border-accent-primary"
              : "bg-background-secondary text-text-secondary border-border-default hover:border-accent-primary hover:text-text-primary"
          )}
        >
          <Clock className="w-4 h-4" />
          Custom
          <ChevronDown className={cn("w-3.5 h-3.5 transition-transform", showCustom && "rotate-180")} />
        </button>
      </div>

      {/* Custom Time Picker */}
      {showCustom && (
        <div className="p-4 bg-background-secondary border border-border-default rounded-lg">
          <div className="flex items-center gap-2">
            <select
              value={customHour}
              onChange={(e) => setCustomHour(e.target.value)}
              className="px-3 py-2 rounded-lg border border-border-default bg-background-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-accent-primary/50"
            >
              {Array.from({ length: 24 }, (_, i) => (
                <option key={i} value={i.toString().padStart(2, "0")}>
                  {i.toString().padStart(2, "0")}
                </option>
              ))}
            </select>
            <span className="text-text-secondary text-lg">:</span>
            <select
              value={customMinute}
              onChange={(e) => setCustomMinute(e.target.value)}
              className="px-3 py-2 rounded-lg border border-border-default bg-background-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-accent-primary/50"
            >
              {["00", "15", "30", "45"].map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
            <button
              onClick={handleCustomTime}
              className="px-4 py-2 rounded-lg bg-accent-primary text-text-inverse text-sm font-medium hover:bg-accent-primary-hover transition-colors"
            >
              Set
            </button>
          </div>
          <p className="text-xs text-text-tertiary mt-2">
            If this time has already passed today, tomorrow will be used.
          </p>
        </div>
      )}

      {/* Selected Time Display */}
      {value && (
        <div className="flex items-center justify-between text-sm">
          <span className="text-text-primary">
            {formatSelectedTime(value)}
          </span>
          {timeRemaining && (
            <span className="text-accent-primary font-medium">
              {timeRemaining}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
